# Generated by Django 3.0.8 on 2021-06-16 23:51

from django.db import migrations, models
import restcon.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(null=True, upload_to=restcon.models.upload_cardapio, verbose_name='Cardápio')),
            ],
        ),
    ]
